### ISSUE TITLE
App threw an error during load

### ISSUE THREAD

**Issue by dhrn** [artiebits/unix-print#16]
Electron app throwing on start
```

[0] App threw an error during load
[0] 
[0] Error: Attempted to register a second handler for 'print-pdf'
[0]     at IpcMainImpl.handle (node:electron/js2c/browser_init:193:337)
[0]     at Object../apps/electron-app/src/app/events/electron.events.ts (/dist/apps/electron-app/main.js:326:47)
[0]     at __webpack_require__ (/dist/apps/electron-app/main.js:3647:41)
[0]     at /dist/apps/electron-app/main.js:3703:85
[0]     at /dist/apps/electron-app/main.js:3754:3
[0]     at Object.<anonymous> (/dist/apps/electron-app/main.js:3759:12)
[0]     at Module._compile (node:internal/modules/cjs/loader:1116:14)
[0]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
[0]     at Module.load (node:internal/modules/cjs/loader:988:32)
[0]     at Module._load (node:internal/modules/cjs/loader:829:12)

```

**Comment by artiebits** [comment]
could you please provide a piece of code that throws the error? thanks!
